### ISSUE TITLE
Mongo DB backup/replicatie instellen

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-admin-deployment#9]

**Comment by robstek** [comment]
in C:\MongoDB staat een backup script dat in de Windows Task Scheduler wordt gebruikt (nightly backup @ 01:00 uur).
Verwijst eerst naar C:\tmp, als backuppen  goed gaat naar C:\MongoDB\dump\scheduled\

**Comment by robstek** [comment]
NB
Mongo replicatie heeft alleen zin als er meerdere machines worden ingezet met elk een draaiende Mongo instantie

**Comment by HermanAssink** [comment]
Dus nvt
